<?php
session_start();
include 'db.php';

// ── Auth check ─────────────────────────────────────────────────────────────
if (!isset($_SESSION['user_id'])) {
    header('Location: index.php');
    exit;
}

// Session timeout
$timeout_duration = 1800;
if (isset($_SESSION['LAST_ACTIVITY']) && (time() - $_SESSION['LAST_ACTIVITY']) > $timeout_duration) {
    session_unset(); session_destroy();
    header('Location: index.php');
    exit;
}
$_SESSION['LAST_ACTIVITY'] = time();

// ── Logging helper (mirrors index.php) ────────────────────────────────────
if (!function_exists('log_message')) {
    function log_message($level, $message) {
        $timestamp = date('Y-m-d H:i:s');
        $log_entry = "[{$timestamp}] [{$level}] {$message}\n";
        error_log($log_entry, 3, 'logs/app.log');
    }
}

$message  = '';
$max_size = 5 * 1024 * 1024;

// ── Download per-school forecast CSV ──────────────────────────────────────
if (isset($_GET['download_school_csv'])) {
    $f = 'forecast_per_school.csv';
    if (file_exists($f)) {
        $ts = date('Y-m-d_H-i-s');
        header('Content-Type: text/csv');
        header('Content-Disposition: attachment; filename="ncr_shs_per_school_forecast_' . $ts . '.csv"');
        header('Content-Length: ' . filesize($f));
        readfile($f);
        exit;
    }
    $message = "<div class='error'>❌ No forecast file found. Generate a forecast first.</div>";
}

// ── Handle per-school CSV upload ───────────────────────────────────────────
$isAjax = isset($_POST['ajax']);

if (isset($_FILES['file_school']) && $_FILES['file_school']['error'] === UPLOAD_ERR_OK) {
    try {
        $ext = strtolower(pathinfo($_FILES['file_school']['name'], PATHINFO_EXTENSION));
        if ($ext !== 'csv') throw new Exception('Only CSV files are allowed.');
        if ($_FILES['file_school']['size'] > $max_size) throw new Exception('File exceeds 5MB limit.');

        $handle = fopen($_FILES['file_school']['tmp_name'], 'r');
        $header = fgetcsv($handle);
        $required = ['School_ID','School_Name','Year','Academic_Enrollees','TVL_Enrollees','Total_Enrollees'];
        $missing  = array_diff($required, $header);
        if (!empty($missing)) throw new Exception('Missing columns: ' . implode(', ', $missing));

        $firstRow = fgetcsv($handle);
        if (!$firstRow) throw new Exception('CSV has no data rows.');
        fclose($handle);

        if (!move_uploaded_file($_FILES['file_school']['tmp_name'], 'NCR_SHS_Per_School_Enrollees.csv'))
            throw new Exception('Failed to save file.');

        log_message('INFO', "Per-school CSV uploaded by user {$_SESSION['user_id']}");
        $message = "<div class='success'>✅ Per-school dataset uploaded successfully. Click <strong>Generate Forecast</strong> to run the forecast.</div>";
    } catch (Exception $e) {
        $message = "<div class='error'>❌ " . htmlspecialchars($e->getMessage()) . "</div>";
        log_message('ERROR', 'Per-school upload: ' . $e->getMessage());
    }
    if ($isAjax) { echo $message; exit; }
}

// ── Handle Generate Forecast ───────────────────────────────────────────────
if (isset($_POST['run'])) {
    if (!file_exists('NCR_SHS_Per_School_Enrollees.csv')) {
        $message = "<div class='error'>❌ No per-school dataset found. Please upload one first.</div>";
    } else {
        $output = shell_exec("python forecast.py 2>&1");
        if (strpos($output, 'SUCCESS') !== false) {
            log_message('INFO', "Per-school forecast generated by user {$_SESSION['user_id']}");
            $message = "<div class='success'>✅ Per-school forecast generated successfully.</div>";
        } else {
            log_message('ERROR', "Per-school forecast failed: $output");
            $message = "<div class='error'>❌ Forecast failed. Check system logs for details.</div>";
        }
    }
    if ($isAjax) { echo $message; exit; }
}

// ── Handle Clear ───────────────────────────────────────────────────────────
if (isset($_POST['clear'])) {
    foreach (['forecast_per_school.csv','NCR_SHS_Per_School_Enrollees.csv','forecast.csv','forecast_accuracy.json'] as $f) {
        if (file_exists($f)) unlink($f);
    }
    log_message('INFO', "Per-school forecast cleared by user {$_SESSION['user_id']}");
    $message = "<div class='success'>✅ All per-school data cleared.</div>";
    if ($isAjax) { echo $message; exit; }
}

// ── Load per-school forecast data ──────────────────────────────────────────
$perSchoolExists = file_exists('forecast_per_school.csv');
$psRows = []; $psYears = []; $firstPsYear = '';

if ($perSchoolExists) {
    $handle = fopen('forecast_per_school.csv', 'r');
    $hdr    = array_map('trim', fgetcsv($handle));
    while (($row = fgetcsv($handle)) !== false) {
        $row = array_map('trim', $row);          // strip any whitespace/BOM
        $combined = array_combine($hdr, $row);
        $combined['Year'] = (int)floatval($combined['Year']); // handle "2026.0" safely
        $psRows[] = $combined;
    }
    fclose($handle);
    $psYears = array_values(array_unique(array_column($psRows, 'Year')));
    sort($psYears);
    $firstPsYear = $psYears[0] ?? 0;
}

// ── Load accuracy metrics ───────────────────────────────────────────────────
$accuracy = null;
if (file_exists('forecast_accuracy.json')) {
    $accuracy = json_decode(file_get_contents('forecast_accuracy.json'), true);
}

// ── Dataset status ─────────────────────────────────────────────────────────
$datasetExists = file_exists('NCR_SHS_Per_School_Enrollees.csv');
$schoolCount = 0;
if ($datasetExists) {
    $lines = file('NCR_SHS_Per_School_Enrollees.csv', FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
    $ids = [];
    for ($i = 1; $i < count($lines); $i++) {
        $cols = str_getcsv($lines[$i]);
        if (isset($cols[0])) $ids[$cols[0]] = true;
    }
    $schoolCount = count($ids);
}
?>
<!DOCTYPE html>
<html>
<head>
    <title>Per-School Forecast — NCR SHS</title>
    <link rel="stylesheet" href="style.css">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>
<body>

<?php $current_page = 'school'; include 'nav.php'; ?>

<div class="page-wrapper">

    <div class="page-hero">
        <div class="page-hero-text">
            <h1>Per-School Enrollment Forecast</h1>
            <p>Department of Education — NCR &nbsp;|&nbsp; School-Level Resource Planning</p>
        </div>
        <?php if ($perSchoolExists && $accuracy): ?>
        <div class="page-hero-badge">
            <div class="badge-label">Model Accuracy</div>
            <div class="badge-value"><?php echo $accuracy['accuracy']; ?>%</div>
            <div class="badge-sub">MAPE: <?php echo $accuracy['mape']; ?>% · <?php echo $accuracy['school_count'] ?? $schoolCount; ?> schools</div>
        </div>
        <?php endif; ?>
    </div>

    <?php if ($message) echo "<div style='margin-bottom:16px;'>$message</div>"; ?>

    <div class="two-col">

        <!-- LEFT: Controls panel -->
        <div>
            <!-- Dataset status -->
            <div class="card" style="margin-bottom:16px;">
                <h3 style="font-family:var(--font-body); font-size:0.9em; font-weight:700; color:var(--text-primary); margin-bottom:14px; text-transform:uppercase; letter-spacing:0.5px;">Dataset Status</h3>
                <?php if ($datasetExists): ?>
                    <span class="status-badge badge-ok" id="datasetStatusBadge">✅ Dataset loaded — <?php echo $schoolCount; ?> schools</span>
                    <p id="datasetFileInfo" style="font-size:0.82em; color:#666; margin:8px 0 0;">
                        File: <code>NCR_SHS_Per_School_Enrollees.csv</code>
                    </p>
                <?php else: ?>
                    <span class="status-badge badge-no" id="datasetStatusBadge">⚠️ No dataset uploaded</span>
                    <p id="datasetFileInfo" style="font-size:0.82em; color:#666; margin:8px 0 0; display:none;">
                        File: <code>NCR_SHS_Per_School_Enrollees.csv</code>
                    </p>
                <?php endif; ?>

                <hr style="margin:16px 0;">

                <!-- Upload -->
                <p style="font-size:0.85em; font-weight:700; color:#003D99; margin:0 0 8px;">Upload New Dataset</p>
                <div class="file-drop" id="dropZone">
                    <input type="file" id="csvFileSchool" accept=".csv">
                    <label for="csvFileSchool">📂 Click to browse or drag & drop CSV</label>
                    <div class="file-name-display" id="fileNameDisplay">No file selected</div>
                </div>
                <div id="uploadMsg" style="margin-top:8px;"></div>
                <button type="button" class="action-btn btn-generate" onclick="handleSchoolUpload()" style="margin-top:10px; text-transform:none; letter-spacing:0; font-size:0.88em; padding:10px;">
                    📤 Upload Dataset
                </button>

                <hr style="margin:16px 0;">
                <p style="font-size:0.8em; font-weight:700; color:#666; margin:0 0 6px;">Required CSV columns:</p>
                <pre style="font-size:0.75em; padding:10px; margin:0;">School_ID, School_Name, City, Year,
Academic_Enrollees, TVL_Enrollees,
Total_Enrollees</pre>
            </div>

            <!-- Actions -->
            <div class="card">
                <h3 style="font-family:var(--font-body); font-size:0.9em; font-weight:700; color:var(--text-primary); margin-bottom:14px; text-transform:uppercase; letter-spacing:0.5px;">Actions</h3>
                <button type="button" class="action-btn btn-generate" onclick="handleGenerate()">
                    ⚡ Generate Per-School Forecast
                </button>
                <div id="generateMsg" style="margin-bottom:10px;"></div>

                <?php if ($perSchoolExists): ?>
                <a href="?download_school_csv=1" style="text-decoration:none;">
                    <button type="button" class="action-btn btn-download-school" style="text-transform:none; letter-spacing:0;">
                        📊 Download Forecast CSV
                    </button>
                </a>
                <button type="button" class="action-btn" onclick="downloadPDF()"
                    style="background:linear-gradient(135deg,#5B21B6,#7C3AED);color:#fff;
                           box-shadow:0 5px 14px rgba(91,33,182,0.35); text-transform:none; letter-spacing:0;">
                    📄 Download PDF Report
                </button>
                <?php endif; ?>

                <button type="button" class="action-btn btn-clear-school" onclick="handleClear()" style="text-transform:none; letter-spacing:0; margin-top:4px; font-size:0.85em; padding:10px;">
                    🗑️ Clear All Data
                </button>
                <div id="clearMsg"></div>
            </div>
        </div>

        <!-- RIGHT: Results -->
        <div>
            <?php if ($perSchoolExists && !empty($psRows)): ?>

            <!-- Summary chips for first forecast year -->
            <?php
            $firstYearRows = array_filter($psRows, fn($r) => $r['Year'] == $firstPsYear);
            $totalEnrollees  = array_sum(array_column(iterator_to_array((function() use($firstYearRows) { yield from $firstYearRows; })()), 'Projected_Enrollees'));
            $totalAcadRooms  = array_sum(array_column(iterator_to_array((function() use($firstYearRows) { yield from $firstYearRows; })()), 'Academic_Classrooms'));
            $totalTVLRooms   = array_sum(array_column(iterator_to_array((function() use($firstYearRows) { yield from $firstYearRows; })()), 'TVL_Classrooms'));
            $totalAcadTeach  = array_sum(array_column(iterator_to_array((function() use($firstYearRows) { yield from $firstYearRows; })()), 'Academic_Teachers'));
            $totalTVLTeach   = array_sum(array_column(iterator_to_array((function() use($firstYearRows) { yield from $firstYearRows; })()), 'TVL_Teachers'));
            $schoolsInYear   = count($firstYearRows);

            // Simpler re-computation
            $fy = array_values(array_filter($psRows, fn($r) => (int)$r['Year'] == $firstPsYear));
            $totalEnrollees = array_sum(array_column($fy, 'Projected_Enrollees'));
            $totalAcadRooms = array_sum(array_column($fy, 'Academic_Classrooms'));
            $totalTVLRooms  = array_sum(array_column($fy, 'TVL_Classrooms'));
            $totalAcadTeach = array_sum(array_column($fy, 'Academic_Teachers'));
            $totalTVLTeach  = array_sum(array_column($fy, 'TVL_Teachers'));
            $schoolsInYear  = count($fy);
            ?>
            <div class="summary-chips">
                <div class="chip">
                    <div class="chip-label">Schools Forecasted</div>
                    <div class="chip-value"><?php echo $schoolsInYear; ?></div>
                    <div style="font-size:0.75em; color:var(--text-muted);">for <?php echo $firstPsYear; ?></div>
                </div>
                <div class="chip">
                    <div class="chip-label">Total Projected Enrollees</div>
                    <div class="chip-value"><?php echo number_format($totalEnrollees); ?></div>
                </div>
                <div class="chip accent">
                    <div class="chip-label">Total Classrooms</div>
                    <div class="chip-value"><?php echo number_format($totalAcadRooms + $totalTVLRooms); ?></div>
                    <div style="font-size:0.75em; color:var(--text-muted);">Acad: <?php echo number_format($totalAcadRooms); ?> | TVL: <?php echo number_format($totalTVLRooms); ?></div>
                </div>
                <div class="chip warning">
                    <div class="chip-label">Total Teachers Needed</div>
                    <div class="chip-value"><?php echo number_format($totalAcadTeach + $totalTVLTeach); ?></div>
                    <div style="font-size:0.75em; color:var(--text-muted);">Acad: <?php echo number_format($totalAcadTeach); ?> | TVL: <?php echo number_format($totalTVLTeach); ?></div>
                </div>
            </div>

            <!-- Table controls -->
            <div class="card">
                <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:14px; flex-wrap:wrap; gap:10px;">
                    <h3 style="margin:0;">📋 Per-School Breakdown</h3>
                </div>
                <div style="display:flex; gap:10px; align-items:center; flex-wrap:wrap; margin-bottom:14px;">
                    <label style="font-size:0.8em; font-weight:700; color:var(--text-muted); text-transform:uppercase; letter-spacing:0.5px;">Year:</label>
                    <select id="yearFilter" class="tbl-select" onchange="filterTable()">
                        <?php foreach ($psYears as $y): ?>
                            <option value="<?php echo (int)$y; ?>"><?php echo (int)$y; ?></option>
                        <?php endforeach; ?>
                    </select>
                    <input type="text" id="schoolSearch" class="tbl-search"
                        placeholder="🔍 Search school or city..."
                        onkeyup="filterTable()">
                </div>

                <div style="max-height:500px; overflow-y:auto;" class="table-wrapper">
                    <table  style="width:100%; border-collapse:collapse;">
                        <thead>
                            <tr>
                                <th onclick="sortTable(0)">School ↕</th>
                                <th onclick="sortTable(1)">City ↕</th>
                                <th onclick="sortTable(2)" style="text-align:right;">Enrollees ↕</th>
                                <th style="text-align:right;">95% CI</th>
                                <th onclick="sortTable(4)" style="text-align:right;">Acad. Rooms ↕</th>
                                <th onclick="sortTable(5)" style="text-align:right;">TVL Rooms ↕</th>
                                <th onclick="sortTable(6)" style="text-align:right;">Acad. Teachers ↕</th>
                                <th onclick="sortTable(7)" style="text-align:right;">TVL Teachers ↕</th>
                            </tr>
                        </thead>
                        <tbody id="schoolTbody">
                        <?php foreach ($psRows as $r): ?>
                            <tr data-year="<?php echo (int)$r['Year']; ?>"
                                style="<?php echo (int)$r['Year'] == $firstPsYear ? '' : 'display:none;'; ?>">
                                <td style="text-align:left; font-weight:500;"><?php echo htmlspecialchars($r['School_Name']); ?></td>
                                <td style="text-align:left; color:#666; font-size:0.9em;"><?php echo htmlspecialchars($r['City'] ?? ''); ?></td>
                                <td><?php echo number_format($r['Projected_Enrollees']); ?></td>
                                <td style="color:#888; font-size:0.85em;"><?php echo number_format($r['Lower_Bound']); ?>–<?php echo number_format($r['Upper_Bound']); ?></td>
                                <td><?php echo number_format($r['Academic_Classrooms']); ?></td>
                                <td><?php echo number_format($r['TVL_Classrooms']); ?></td>
                                <td><?php echo number_format($r['Academic_Teachers']); ?></td>
                                <td><?php echo number_format($r['TVL_Teachers']); ?></td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
                <p style="font-size:0.75em; color:var(--text-muted); margin:10px 0 0; text-align:right;">
                    All figures are model projections. Actual allocation decisions rest with DepEd planners.
                </p>
            </div>

            <?php else: ?>
            <div class="card">
                <div class="empty-state">
                    <div class="icon">🏫</div>
                    <p style="font-size:1.1em; font-weight:600; color:#555; margin-bottom:8px;">No forecast data yet</p>
                    <p style="color:#999;">Upload a per-school dataset and click <strong>Generate Per-School Forecast</strong> to see individual school resource projections here.</p>
                </div>
            </div>
            <?php endif; ?>
        </div>
    </div>
</div>

<script>
// ── File drag & drop ────────────────────────────────────────────────────────
const dropZone  = document.getElementById('dropZone');
const fileInput = document.getElementById('csvFileSchool');
const fileLabel = document.getElementById('fileNameDisplay');

fileInput.addEventListener('change', () => {
    fileLabel.textContent = fileInput.files[0]?.name || 'No file selected';
});
dropZone.addEventListener('dragover',  e => { e.preventDefault(); dropZone.classList.add('drag-over'); });
dropZone.addEventListener('dragleave', ()  => dropZone.classList.remove('drag-over'));
dropZone.addEventListener('drop', e => {
    e.preventDefault(); dropZone.classList.remove('drag-over');
    if (e.dataTransfer.files[0]) {
        const dt = new DataTransfer();
        dt.items.add(e.dataTransfer.files[0]);
        fileInput.files = dt.files;
        fileLabel.textContent = e.dataTransfer.files[0].name;
    }
});

// ── Upload ──────────────────────────────────────────────────────────────────
function handleSchoolUpload() {
    const file = fileInput.files[0];
    const msg  = document.getElementById('uploadMsg');
    if (!file) { msg.innerHTML = "<div class='error'>❌ Please select a file first.</div>"; return; }

    const fd = new FormData();
    fd.append('file_school', file);
    fd.append('ajax', '1');
    msg.innerHTML = "<div style='color:#003D99; padding:8px;'>⏳ Uploading…</div>";

    fetch('school_forecast.php', { method:'POST', body: fd })
        .then(r => r.text())
        .then(data => {
            msg.innerHTML = data;
            fileInput.value = '';
            fileLabel.textContent = 'No file selected';

            // If upload succeeded, update the status badge immediately without a page reload
            if (data.includes('✅')) {
                const badge    = document.getElementById('datasetStatusBadge');
                const fileInfo = document.getElementById('datasetFileInfo');
                if (badge) {
                    badge.className = 'status-badge badge-ok';
                    badge.textContent = '✅ Dataset loaded';
                }
                if (fileInfo) {
                    fileInfo.style.display = '';
                }
                // Also enable the Generate button visually
                const genBtn = document.getElementById('generateBtn');
                if (genBtn) genBtn.disabled = false;
            }
        })
        .catch(e  => { msg.innerHTML = "<div class='error'>❌ " + e.message + "</div>"; });
}

// ── Generate forecast ───────────────────────────────────────────────────────
function handleGenerate() {
    const msg = document.getElementById('generateMsg');
    msg.innerHTML = "<div style='color:#003D99; padding:8px;'>⏳ Running forecast for all schools… this may take a moment.</div>";

    const fd = new FormData();
    fd.append('run', '1');
    fd.append('ajax', '1');

    fetch('school_forecast.php', { method:'POST', body: fd })
        .then(r => r.text())
        .then(data => {
            msg.innerHTML = data;
            if (data.includes('success') || data.includes('✅')) {
                setTimeout(() => window.location.href = 'school_forecast.php', 1500);
            }
        })
        .catch(e => { msg.innerHTML = "<div class='error'>❌ " + e.message + "</div>"; });
}

// ── Clear ───────────────────────────────────────────────────────────────────
function handleClear() {
    if (!confirm('Clear all per-school forecast data and the uploaded dataset?')) return;
    const msg = document.getElementById('clearMsg');
    msg.innerHTML = "<div style='color:#003D99; padding:8px;'>⏳ Clearing data…</div>";
    const fd  = new FormData();
    fd.append('clear', '1');
    fd.append('ajax', '1');

    fetch('school_forecast.php', { method:'POST', body: fd })
        .then(r => {
            if (!r.ok) throw new Error('Server error: ' + r.status);
            return r.text();
        })
        .then(data => {
            msg.innerHTML = data;
            // Only reload if the response confirms success
            if (data.includes('✅')) {
                setTimeout(() => window.location.href = 'school_forecast.php', 1200);
            }
        })
        .catch(e  => { msg.innerHTML = "<div class='error'>❌ " + e.message + "</div>"; });
}

// ── PDF Report ──────────────────────────────────────────────────────────────
function downloadPDF() {
    const url = 'school_forecast_pdf.php';
    const w = window.open(url, '_blank', 'width=1200,height=800,scrollbars=yes,resizable=yes');
    if (!w) {
        alert('Pop-up blocked. Please allow pop-ups for this site, or hold Ctrl and click the button again.');
    }
}

// ── Table: filter by year + search ─────────────────────────────────────────
function filterTable() {
    const year   = document.getElementById('yearFilter')?.value || '';
    const search = (document.getElementById('schoolSearch')?.value || '').toLowerCase();
    document.querySelectorAll('#schoolTbody tr').forEach(row => {
        // Compare as integers to avoid any string/float mismatch
        const matchYear   = !year || parseInt(row.dataset.year) === parseInt(year);
        const matchSearch = !search || row.textContent.toLowerCase().includes(search);
        row.style.display = (matchYear && matchSearch) ? '' : 'none';
    });
}

// ── Table: sort ─────────────────────────────────────────────────────────────
let sortDir = {};
function sortTable(col) {
    const tbody = document.getElementById('schoolTbody');
    if (!tbody) return;
    const rows = Array.from(tbody.querySelectorAll('tr'));
    const asc  = !sortDir[col];
    sortDir = {};
    sortDir[col] = asc;

    rows.sort((a, b) => {
        const at = a.cells[col]?.innerText.replace(/[,–]/g,'').trim() || '';
        const bt = b.cells[col]?.innerText.replace(/[,–]/g,'').trim() || '';
        const an = parseFloat(at), bn = parseFloat(bt);
        if (!isNaN(an) && !isNaN(bn)) return asc ? an - bn : bn - an;
        return asc ? at.localeCompare(bt) : bt.localeCompare(at);
    });
    rows.forEach(r => tbody.appendChild(r));
}
</script>

<?php $bg_mode = 'dashboard'; include 'bg_canvas.php'; ?>
</body>
</html>